/**
 * Zod mirror of normalized-record.schema.json.
 *
 * Used by orchestrator/ and reporting/ (and any future TS extractor) so a
 * record read out of Postgres — or about to be written into it — is
 * validated against the exact same envelope Python extractors build against.
 *
 * The SourceType enum below is GENERATED from the canonical schema:
 *   - contracts/normalized-record.schema.json           (source of truth)
 *   - packages-py/contracts/normalized_record.py        (Python/Pydantic mirror)
 *
 * Do not add a source_type by hand here. Add it to the canonical schema and run
 * `python3 scripts/sync_contracts.py --write`; CI runs `--check` and fails on
 * drift. This used to be a request to "keep this in lockstep", and it did not
 * hold: the canonical schema was missing `ileapp_record` while both mirrors
 * declared it, so every iLEAPP record passed this model and was then rejected
 * by the JSON schema the adapters load.
 *
 * The object fields are still hand-written, because their type expressions are
 * genuinely language-specific. The sync script asserts the field *names* match
 * the schema even though it does not generate them.
 */

import { z } from "zod";

export const SourceType = z.enum([
  // SOURCE_TYPE GENERATED FROM contracts/normalized-record.schema.json
  // generated by scripts/sync_contracts.py -- do not edit by hand; add new values to the canonical schema and re-run with --write
  "crash_report",
  "siri_feedback",
  "sfa_analytics",
  "xp_amp_telemetry",
  "safari_history",
  "sms_attachment",
  "network_usage",
  "gcloud_log",
  "syslog_line",
  "mvt_ioc_detection",
  "timestamp_anomaly",
  "ileapp_record",
  // END SOURCE_TYPE
]);
export type SourceType = z.infer<typeof SourceType>;

export const NormalizedRecord = z
  .object({
    incident_id: z.string().nullable().default(null),
    source_type: SourceType,
    event_time: z.string().datetime().nullable().default(null),
    bug_type: z.string().nullable().default(null),
    process_name: z.string().nullable().default(null),
    pid: z.number().int().nullable().default(null),
    bundle_id: z.string().nullable().default(null),
    fields: z.record(z.string(), z.unknown()).default({}),
  })
  .strict();

export type NormalizedRecord = z.infer<typeof NormalizedRecord>;
